spring:
  application:
    name: CodeHawk

  # File Upload Settings
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  # Database settings
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    # retry for database connection on error
    hikari:
      initializationFailTimeout: -1

#JPA settings
  jpa.hibernate.ddl-auto: update

server:
  port: 8080

python:
  execution:
    timeout: 10

backend:
  url: http://localhost:8080/api/execution/result